### ISSUE TITLE
error: no member named 'setOutputPath'

### ISSUE THREAD

**Issue by dcg87** [tiehuis/zig-gameboy#1]
**git clone --recursive https://github.com/tiehuis/zig-gameboy**

_Cloning into 'zig-gameboy'...
remote: Enumerating objects: 75, done.
remote: Total 75 (delta 0), reused 0 (delta 0), pack-reused 75
Unpacking objects: 100% (75/75), done.
Submodule 'lib/zig-sdl2' (https://github.com/tiehuis/zig-sdl2) registered for path 'lib/zig-sdl2'
Cloning into '/Users/Duncan/Desktop/zig/zig-gameboy/lib/zig-sdl2'...
remote: Enumerating objects: 3, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 117 (delta 0), reused 0 (delta 0), pack-reused 114        
Receiving objects: 100% (117/117), 41.86 KiB | 2.79 MiB/s, done.
Resolving deltas: 100% (62/62), done.
Submodule path 'lib/zig-sdl2': checked out '02ce9ae66a188c1f4f96cd926f72a5bc81922466'_

**cd zig-gameboy
zig build**

_/Users/Duncan/Desktop/zig/zig-gameboy/build.zig:11:8: error: no member named 'setOutputPath' in struct 'std.build.LibExeObjStep'
    exe.setOutputPath("./gameboy");_

**Comment by tiehuis** [comment]
The build interface has changed slightly since the last update. I'll update the repository shortly.

**Comment by tiehuis** [comment]
Just a note, this isn't complete and will crash at a certain point on a simple rom. I probably won't be doing any more work on this currently, but it does build under latest master now.
